import Providers from "@/app/providers";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "@/styles/globalStyles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
};

export default RootLayout;
