import { IReactChildren } from "@/app/_interfaces/core";
import Providers from "@/app/providers";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globalStyles.css";
import { ReactElement } from "react";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const Layout = ({ children }: IReactChildren): ReactElement => {
    return (
        <html lang="en">
            <body style={inter.style}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
};

export default Layout;
